"""update in product model

Revision ID: 2018c37c7c6d
Revises: f60306273b3c
Create Date: 2026-01-22 13:07:43.740065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2018c37c7c6d'
down_revision: Union[str, Sequence[str], None] = 'f60306273b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('hsn_code', sa.String(length=255), nullable=True))
    op.drop_column('products', 'hsm_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('hsm_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('products', 'hsn_code')
    # ### end Alembic commands ###
