"""update in sub_category model

Revision ID: 6b7f7a372f2a
Revises: ab369c4ec71f
Create Date: 2026-01-21 17:32:24.054813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7f7a372f2a'
down_revision: Union[str, Sequence[str], None] = 'ab369c4ec71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_categories', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('sub_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_categories', 'deleted_at')
    op.drop_column('sub_categories', 'is_delete')
    # ### end Alembic commands ###
