"""change in product model

Revision ID: 93cad9c01099
Revises: caf8865ca634
Create Date: 2026-01-20 14:03:09.932853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cad9c01099'
down_revision: Union[str, Sequence[str], None] = 'caf8865ca634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'short_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'long_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'hsm_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'sku_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_products_hsm_code'), table_name='products')
    op.drop_index(op.f('ix_products_short_description'), table_name='products')
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=False)
    op.create_index(op.f('ix_products_short_description'), 'products', ['short_description'], unique=False)
    op.create_index(op.f('ix_products_hsm_code'), 'products', ['hsm_code'], unique=False)
    op.alter_column('products', 'sku_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'hsm_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'long_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'short_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
