"""create model main and sub category

Revision ID: ab369c4ec71f
Revises: 90cc8a9f3be8
Create Date: 2026-01-21 15:43:39.765058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab369c4ec71f'
down_revision: Union[str, Sequence[str], None] = '90cc8a9f3be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uu_id', sa.String(length=255), nullable=False),
    sa.Column('main_category_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('main_category_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_categories_id'), 'main_categories', ['id'], unique=False)
    op.create_index(op.f('ix_main_categories_slug'), 'main_categories', ['slug'], unique=False)
    op.create_index(op.f('ix_main_categories_uu_id'), 'main_categories', ['uu_id'], unique=True)
    op.create_table('sub_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('uu_id', sa.String(length=255), nullable=False),
    sa.Column('sub_category_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sub_category_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_categories_category_id'), 'sub_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_sub_categories_id'), 'sub_categories', ['id'], unique=False)
    op.create_index(op.f('ix_sub_categories_slug'), 'sub_categories', ['slug'], unique=False)
    op.create_index(op.f('ix_sub_categories_uu_id'), 'sub_categories', ['uu_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_categories_uu_id'), table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_slug'), table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_id'), table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_category_id'), table_name='sub_categories')
    op.drop_table('sub_categories')
    op.drop_index(op.f('ix_main_categories_uu_id'), table_name='main_categories')
    op.drop_index(op.f('ix_main_categories_slug'), table_name='main_categories')
    op.drop_index(op.f('ix_main_categories_id'), table_name='main_categories')
    op.drop_table('main_categories')
    # ### end Alembic commands ###
