"""create product_images table

Revision ID: caf8865ca634
Revises: 3e24eb3a89fb
Create Date: 2026-01-20 13:08:54.012177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf8865ca634'
down_revision: Union[str, Sequence[str], None] = '3e24eb3a89fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_image', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.drop_index(op.f('ix_categories_slug_not_deleted'), table_name='categories', postgresql_where='(is_delete = false)')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.drop_index(op.f('ix_products_product_short_name_not_deleted'), table_name='products', postgresql_where='(is_delete = false)')
    op.create_index(op.f('ix_products_hsm_code'), 'products', ['hsm_code'], unique=False)
    op.create_index(op.f('ix_products_product_short_name'), 'products', ['product_short_name'], unique=False)
    op.create_index(op.f('ix_products_short_description'), 'products', ['short_description'], unique=False)
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=False)
    op.drop_index(op.f('ix_uoms_uom_short_name_not_deleted'), table_name='uoms', postgresql_where='(is_delete = false)')
    op.create_index(op.f('ix_uoms_uom_short_name'), 'uoms', ['uom_short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uoms_uom_short_name'), table_name='uoms')
    op.create_index(op.f('ix_uoms_uom_short_name_not_deleted'), 'uoms', ['uom_short_name'], unique=True, postgresql_where='(is_delete = false)')
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    op.drop_index(op.f('ix_products_short_description'), table_name='products')
    op.drop_index(op.f('ix_products_product_short_name'), table_name='products')
    op.drop_index(op.f('ix_products_hsm_code'), table_name='products')
    op.create_index(op.f('ix_products_product_short_name_not_deleted'), 'products', ['product_short_name'], unique=True, postgresql_where='(is_delete = false)')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug_not_deleted'), 'categories', ['slug'], unique=True, postgresql_where='(is_delete = false)')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
