"""update in product and category  model

Revision ID: cb959edfd487
Revises: 6b7f7a372f2a
Create Date: 2026-01-22 11:26:38.574374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb959edfd487'
down_revision: Union[str, Sequence[str], None] = '6b7f7a372f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('main_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_categories_main_category_id'), 'categories', ['main_category_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'main_categories', ['main_category_id'], ['id'])
    op.add_column('products', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_sub_category_id'), 'products', ['sub_category_id'], unique=False)
    op.create_foreign_key(None, 'products', 'sub_categories', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_sub_category_id'), table_name='products')
    op.drop_column('products', 'sub_category_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_main_category_id'), table_name='categories')
    op.drop_column('categories', 'main_category_id')
    # ### end Alembic commands ###
