"""update models

Revision ID: e8f14c997264
Revises: e6d58257b7c6
Create Date: 2026-01-19 17:27:14.644608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f14c997264'
down_revision: Union[str, Sequence[str], None] = 'e6d58257b7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.drop_index(op.f('ix_products_product_short_name'), table_name='products')
    op.create_index(op.f('ix_products_product_short_name'), 'products', ['product_short_name'], unique=False)
    op.drop_index(op.f('ix_uoms_uom_short_name'), table_name='uoms')
    op.create_index(op.f('ix_uoms_uom_short_name'), 'uoms', ['uom_short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uoms_uom_short_name'), table_name='uoms')
    op.create_index(op.f('ix_uoms_uom_short_name'), 'uoms', ['uom_short_name'], unique=True)
    op.drop_index(op.f('ix_products_product_short_name'), table_name='products')
    op.create_index(op.f('ix_products_product_short_name'), 'products', ['product_short_name'], unique=True)
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###
